image:
  file: .gitpod.Dockerfile
tasks:
  - init: >
      cachix use imperial-strontium &&

      (yes | nix develop -c echo devShell build successful) &&
      bash -c "nix-store --export \$(nix-store --query -R --include-outputs \$(nix path-info --all)) > /workspace/nix_export"
  - command: >
      mkdir -p ~/.jupyter &&
      bash -c 'echo c.NotebookApp.allow_origin_pat = \"^.+gitpod.io$\" > ~/.jupyter/jupyter_notebook_config.py' &&

      bash -c "nix-store --import < /workspace/nix_export" &&
      (yes | nix develop -c echo devShell build import successful) &&
      direnv allow

vscode:
  extensions:
    - bbenoist.Nix
    - mkhl.direnv
